import os
import re
from typing import List

# Type Declaration Constants
TYPE_DECLARATION_PATTERN_RE = re.compile(r"^\s*([a-zA-Z][a-zA-Z0-9_]*|'[^']+')\s*:\s*(.+?)\s*\.?\s*$")
TYPE_MARKER_RE = re.compile(r"\$tType|\$[io]|\$int|\$rat|\$real|>")


def build_tptp_problem(conjecture_fof: str,
                       axioms_fof: List[str],
                       problem_name: str = "prob1") -> str:
    """
    Wrap a conjecture and axioms (already in TPTP format) into a complete TPTP problem string.
    """
    filename = os.path.basename(__file__)
    type_declarations: List[str] = []
    axioms: List[str] = []
    lines: List[str] = [f"%Problem: {problem_name}", f"%Generated by: {filename}", ""]

    for idx, axiom in enumerate(axioms_fof, start=1):
        # Determine if the line we are looking at is a type declaration.
        is_type_declaration = determine_typed(axiom)

        if is_type_declaration:
            # We have found a type declaration, save it for later.
            name = f"{problem_name}_type{idx}"
            type_declarations.append(f"tff({name}, type, ( {axiom} ) ).")
        else:
            # We have found a normal formula.
            name = f"{problem_name}_ax{idx}"
            # Treat every possible axiom as tff for better generalisation.
            axioms.append(f"tff({name}, axiom, ( {axiom} ) ).")

    lines.append("% --- Types ---")
    lines.extend(type_declarations)
    lines.append("% --- Axioms ---")
    lines.extend(axioms)
    lines.append(("% --- Conjecture ---"))
    lines.append(f"tff({problem_name}_conj, conjecture, ( {conjecture_fof} ) ).")

    return "\n".join(lines) + "\n"


def determine_typed(axiom_str: str) -> bool:
    """
    Given an TPTP string, determine if the string represents a type declaration.
    """
    axiom_str = axiom_str.strip()
    if axiom_str.startswith(("!", "?")):
        return False
    if "] :" in axiom_str or "]:" in axiom_str:
        return False

    match = TYPE_DECLARATION_PATTERN_RE.match(axiom_str)

    if not match:
        return False

    rhs = match.group(2)

    return bool(TYPE_MARKER_RE.search(rhs))


if __name__ == "__main__":
    conj = "! [X] : ( p(X) => q(X) )"
    axioms = [
        "! [X] : ( p(X) => q(X) )",
        "! [X] : ( q(X) => r(X) )",
    ]

    tptp_str = build_tptp_problem(conj, axioms, problem_name="demo")
    print(tptp_str)
