import os
from typing import List, Optional


def _normalize_statement(statement: str, label: str) -> str:
    """
    Validate and normalize a single full TPTP statement.
    """
    if not isinstance(statement, str):
        raise TypeError(f"{label} must be a string. Got {type(statement).__name__}.")

    normalized = statement.strip()
    if not normalized:
        raise ValueError(f"{label} must not be empty.")

    return normalized


def _normalize_statements(statements: List[str], label: str) -> List[str]:
    """
    Validate and normalize a list of full TPTP statements.
    """
    normalized_statements: List[str] = []
    for idx, statement in enumerate(statements):
        normalized_statements.append(_normalize_statement(statement, f"{label}[{idx}]"))

    return normalized_statements


def build_tptp_problem(conjecture: List[str],
                       axioms: List[str],
                       always_include: Optional[List[str]] = None,
                       problem_name: str = "prob1") -> str:
    """
    Concatenate a conjecture and axioms (already in full TPTP statement) into a complete TPTP problem string.
    """
    filename = os.path.basename(__file__)
    clean_conjectures = _normalize_statements(conjecture, "conjecture")
    clean_axioms = _normalize_statements(axioms, "axioms")
    clean_always_include = _normalize_statements(always_include or [], "always_include")

    lines: List[str] = [
        f"%Problem: {problem_name}",
        f"%Generated by: {filename}",
        "",
    ]

    if clean_always_include:
        lines.append("% --- Types ---")
        lines.extend(clean_always_include)
        lines.append("")

    lines.append("% --- Axioms ---")
    lines.extend(clean_axioms)
    lines.append("")
    lines.append("% --- Conjecture ---")
    lines.extend(clean_conjectures)

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    conj = "fof(t13_tsp_2,conjecture,\n    ! [A] :\n      ( ( ~ v3_struct_0(A)\n        & v2_pre_topc(A)\n        & l1_pre_topc(A) )\n     => ! [B] :\n          ( ( ~ v3_struct_0(B)\n            & v2_t_0topsp(B)\n            & m2_tsp_1(B,A) )\n         => ? [C] :\n              ( v1_pre_topc(C)\n              & m2_tsp_1(C,A)\n              & m2_tsp_1(B,C)\n              & v2_tsp_2(C,A) ) ) ) )."
    axioms = [
        "fof(dt_m2_tsp_1,axiom,\n    ! [A] :\n      ( l1_pre_topc(A)\n     => ! [B] :\n          ( m2_tsp_1(B,A)\n         => l1_pre_topc(B) ) ) ).",
        "fof(l19_tsp_2,axiom,\n    ! [A] :\n      ( ( ~ v3_struct_0(A)\n        & l1_pre_topc(A) )\n     => ! [B] :\n          ( m2_tsp_1(B,A)\n         => m1_subset_1(u1_struct_0(B),k1_zfmisc_1(u1_struct_0(A))) ) ) ).",
    ]

    tptp_str = build_tptp_problem(conj, axioms, problem_name="demo")
    print(tptp_str)
