import os
from typing import List

def build_tptp_problem(conjecture_fof: str,
                       axioms_fof: List[str],
                       problem_name: str = "prob1") -> str:
    """
    Wrap a conjecture and axioms (already in FOF syntax)
    into a complete TPTP problem string.
    """
    # TODO: for now, just concatenate fof(...) lines.
    filename = os.path.basename(__file__)
    lines: List[str] = [f"%Problem: {problem_name}", f"%Generated by: {filename}", "", "% --- Axioms ---"]

    for idx, axiom in enumerate(axioms_fof, start=1):
        name = f"{problem_name}_ax{idx}"
        lines.append(f"fof({name}, axiom, ( {axiom} ) ).")

    lines.append(("% --- Conjecture ---"))
    lines.append(f"fof({problem_name}_conj, conjecture, ( {conjecture_fof} ) ).")

    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    conj = "! [X] : ( p(X) => q(X) )"
    axioms = [
        "! [X] : ( p(X) => q(X) )",
        "! [X] : ( q(X) => r(X) )",
    ]

    tptp_str = build_tptp_problem(conj, axioms, problem_name="demo")
    print(tptp_str)
